spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunflowerZhou/spring-cloud-config
          searchPaths: respo
#          username: sunflowerZhou
#          password: zbb5201314..
      label: master
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8768